### ISSUE TITLE
wxDeprecationWarning

### ISSUE THREAD

**Issue by xoviat** [xoviat/profile-viewer#3]
```
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:334: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_EXIT, lambda evt: self.Close(True))
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:335: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_OPEN, self.OnOpenFile)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:336: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_OPEN_MEMORY, self.OnOpenMemory)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:338: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_PERCENTAGE_VIEW, self.OnPercentageView)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:339: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_UP_VIEW, self.OnUpView)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:340: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_DEEPER_VIEW, self.OnDeeperView)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:341: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_SHALLOWER_VIEW, self.OnShallowerView)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:342: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_ROOT_VIEW, self.OnRootView)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:343: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_BACK_VIEW, self.OnBackView)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:344: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_MORE_SQUARE, self.OnMoreSquareToggle)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:375: wxPyDeprecationWarning: Call to deprecated i
tem. Use :meth:`AddTool` instead.
  longHelp="Open a (c)Profile trace file")
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:385: wxPyDeprecationWarning: Call to deprecated i
tem. Use :meth:`AddTool` instead.
  "Display the root of the current view tree (home view)"))
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:391: wxPyDeprecationWarning: Call to deprecated i
tem. Use :meth:`AddTool` instead.
  "Back to the previously activated node in the call tree"))
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:397: wxPyDeprecationWarning: Call to deprecated i
tem. Use :meth:`AddTool` instead.
  "Go one level up the call tree (highest-percentage parent)"))
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:406: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  self.percentageViewTool.GetId(), self.OnPercentageView)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:414: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  self.viewTypeTool.GetId(), self.OnViewTypeTool)
C:\Program Files\Python36\lib\site-packages\profile_viewer\listviews.py:92: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_LIST_COL_CLICK(self, self.GetId(), self.OnReorder)
C:\Program Files\Python36\lib\site-packages\profile_viewer\listviews.py:93: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_LIST_ITEM_SELECTED(self, self.GetId(), self.OnNodeSelected)
C:\Program Files\Python36\lib\site-packages\profile_viewer\listviews.py:94: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MOTION(self, self.OnMouseMove)
C:\Program Files\Python36\lib\site-packages\profile_viewer\listviews.py:95: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_LIST_ITEM_ACTIVATED(self, self.GetId(), self.OnNodeActivated)
C:\Program Files\Python36\lib\site-packages\squaremap\squaremap.py:124: wxPyDeprecationWarning: Call to deprecated item
EmptyBitmap. Use :class:`wx.Bitmap` instead
  self._buffer = wx.EmptyBitmap(20, 20)  # Have a default buffer ready
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:779: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_CLOSE(self, self.OnCloseWindow)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:264: wxPyDeprecationWarning: Call to deprecated i
tem. Use GetSize instead
  width, height = self.GetSizeTuple()
C:\Program Files\Python36\lib\site-packages\squaremap\squaremap.py:241: wxPyDeprecationWarning: Call to deprecated item
EmptyBitmap. Use :class:`wx.Bitmap` instead
  self._buffer = wx.EmptyBitmap(width, height)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:272: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  self.OnSquareHighlightedMap)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:274: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  self.OnSquareSelectedList)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:275: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  squaremap.EVT_SQUARE_SELECTED(self.squareMap, self.OnSquareSelectedMap)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:276: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  squaremap.EVT_SQUARE_ACTIVATED(self.squareMap, self.OnNodeActivated)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:278: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  squaremap.EVT_SQUARE_ACTIVATED(control, self.OnNodeActivated)
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:280: wxPyDeprecationWarning: Call to deprecated i
tem __call__. Use :meth:`EvtHandler.Bind` instead.
  self.OnSquareHighlightedList)
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py", line 517, in OnPercentageView
    self.SetPercentageView(not self.percentageView)
  File "C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py", line 524, in SetPercentageView
    total = self.adapter.value(self.loader.get_root(self.viewType))
AttributeError: 'NoneType' object has no attribute 'get_root'
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py", line 517, in OnPercentageView
    self.SetPercentageView(not self.percentageView)
  File "C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py", line 524, in SetPercentageView
    total = self.adapter.value(self.loader.get_root(self.viewType))
AttributeError: 'NoneType' object has no attribute 'get_root'
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:730: wxPyDeprecationWarning: Call to deprecated i
tem. Use GetSize instead
  size = self.GetSizeTuple()
C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py:731: wxPyDeprecationWarning: Call to deprecated i
tem. Use GetPosition instead
  position = self.GetPositionTuple()
ERROR:profile_viewer.runsnake:Unable to write window preferences, ignoring: Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\profile_viewer\runsnake.py", line 787, in OnCloseWindow
    os.rename(temp, config)
```

**Comment by xoviat** [comment]
```
            PyFunctionDef('__call__', '(self, *args)',
                deprecated="Use :meth:`EvtHandler.Bind` instead.",
                doc="""\
                    For backwards compatibility with the old ``EVT_*`` functions.
                    Should be called with either (window, func), (window, ID,
                    func) or (window, ID1, ID2, func) parameters depending on the
                    type of the event.
                    """,
                body="""\
                    assert len(args) == 2 + self.expectedIDs
                    id1 = ID_ANY
                    id2 = ID_ANY
                    target = args[0]
                    if self.expectedIDs == 0:
                        func = args[1]
                    elif self.expectedIDs == 1:
                        id1 = args[1]
                        func = args[2]
                    elif self.expectedIDs == 2:
                        id1 = args[1]
                        id2 = args[2]
                        func = args[3]
                    else:
                        raise ValueError("Unexpected number of IDs")
                    self.Bind(target, id1, id2, func)
                    """)
```
